version: "{build}"

environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib
    APPVEYOR_YML_DISABLE_PS_LINUX: true

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - choco install neko --yes
  - choco install haxe --prerelease --source 'https://ci.appveyor.com/nuget/haxe' --yes

  - RefreshEnv

  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"

  - haxelib git hxp https://github.com/openfl/hxp.git
  - haxelib git flurry https://github.com/Aidan63/Flurry.git
  - haxelib git hxtelemetry https://github.com/jcward/hxtelemetry.git
  - haxelib git linc_imgui https://github.com/Aidan63/linc_imgui.git
  - haxelib run flurry install;

build_script:
  - cd "haxelib libpath hxcpp"
  - cd tools\run
  - haxe compile.hxml
  - cd ..\hxcpp
  - haxe compile.hxml

test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - cd engine\test
  - haxe build-cpp.hxml
  - .\bin\cpp\Main.exe

  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-engine.xml))