environment:
  global:
    HAXELIB_ROOT: C:\projects\haxelib

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - cinst neko --version 2.0.0 -y
  - cinst haxe --prerelease --ignore-dependencies -s 'https://ci.appveyor.com/nuget/haxe' -y

  - RefreshEnv

  - mkdir "%HAXELIB_ROOT%"
  - haxelib setup "%HAXELIB_ROOT%"

  - haxelib git hxp https://github.com/openfl/hxp.git
  - haxelib git flurry https://github.com/Aidan63/Flurry.git
  - haxelib git hxtelemetry https://github.com/jcward/hxtelemetry.git
  - haxelib git linc_imgui https://github.com/Aidan63/linc_imgui.git
  - haxelib run flurry install;
  - haxelib set hxp git

test_script:
  - cd "haxelib libpath hxcpp"
  - cd tools\run
  - haxe compile.hxml
  - cd ..\hxcpp
  - haxe compile.hxml

  - cd %APPVEYOR_BUILD_FOLDER%
  - cd engine\test
  - haxe build-cpp.hxml
  - .\bin\cpp\Main.exe

  - ps: $wc = New-Object 'System.Net.WebClient'
  - ps: $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\test-engine.xml))