version: "2"
plugins:
  haxe-checkstyle:
    enabled: true
ratings:
  paths:
    - "engine/src"
    - "engine/test"
    - "tools/parcel"
    - "tools/flurry"
    - "sample/basic"
    - "sample/benchmark"
    - "sample/tetris"