strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.15.x'

- bash: ci/install.sh
  displayName: Install Dependencies
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AGENT_OS: $(Agent.OS)

- bash: ci/test_engine.sh
  displayName: Engine Tests
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AGENT_OS: $(Agent.OS)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: engine/test/test-engine.xml
    searchFolder: $(Build.SourcesDirectory)
    testRunTitle: Engine Tests $(Agent.OS)
    buildPlatform: $(Agent.OS)
    failTaskOnFailedTests: true
