strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'

pool:
  vmImage: $(imageName)

- task: NodeTool@0
  inputs:
    versionSpec: '10.15.x'

steps:
- bash: ci/install_lix.sh
  displayName: Haxe Install
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AGENT_OS: $(Agent.OS)

- bash: |
    cd engine/test
    haxe build-cpp.hxml -D report-name=Engine-Tests-$AGENT_OS
    ./bin/cpp/Main
  displayName: Run unit tests
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AGENT_OS: $(Agent.OS)

- task: PublishTestResults@2
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: engine/test/test-engine.xml
    searchFolder: $(Build.SourcesDirectory)
    testRunTitle: Engine Tests $(Agent.OS)
    buildPlatform: $(Agent.OS)
    failTaskOnFailedTests: true
