strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.14'
    #windows:
      #imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: InstallSSHKey@0
  inputs:
    hostName: github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/
    sshPublicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCl8fzt0pSMHDoFDAMRjIZCkCF4KIFDVLMh+UxXTu8mQsPQbxKgiJDLgbmAwPRoSKjMQD2dJrFuPmeDsB69H4DG8uFqDJypQyvTZPbuk0q2pzw8fjy7R1B8avYvxFwvoe1GTUg431yIbfYQua9LyNz0Yp08PgQcSFyHOHOi+YI9+qZzJEVNo6ah7sO4aEHekhpv84RNLovZH0RJztVJbh83mvti8meOIueBomjBZBlQ5z5h07qY1ovBzEI7U6upsU3P0pYerebe/eC11yFQTEFNQFwqgCR1IR9nb8YQhYbzyxSgpxlf74T006ilwdOXhrHCLgaPJQDlgpDUph2GimSj aidan@aidan
    sshKeySecureFile: id_rsa

- task: NodeTool@0
  inputs:
    versionSpec: '10.15.x'

- bash: ci/install.sh
  displayName: Install Dependencies
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AGENT_OS: $(Agent.OS)

- bash: ci/test_engine.sh
  displayName: Engine Tests
  workingDirectory: $(Build.SourcesDirectory)
  env:
    AGENT_OS: $(Agent.OS)

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: xUnit
    testResultsFiles: test/test-engine.xml
    searchFolder: $(Build.SourcesDirectory)
    testRunTitle: Engine Tests $(Agent.OS)
    buildPlatform: $(Agent.OS)
    failTaskOnFailedTests: true
